name: Update GitHub Pages

on:
  push:
    branches:
       - main

jobs:
  github-pages:
    name: Updates GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: adopt
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run SBT task
        run: sbt mdoc publishToGitHubPages
        env:
          GITHUB_TOKEN: ${{ github.token }}
